version: '3.7'

volumes:
  files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/files
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/mysql
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/backup
  nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/nginx


services:
  fchecker:
    image: eucm/formalz-fchecker:1.0.0
    container_name: formalz-fchecker
    command: /usr/local/bin/javawlp -p 8080 --runServer
    restart: unless-stopped
    hostname: formalz-fchecker

  gameserver:
    image: eucm/formalz-gameserver:1.0.2
    container_name: formalz-gameserver
    restart: unless-stopped
    depends_on:
      - fchecker
      - db
    environment:
      # Fchecker config
      - FORMALZ_FCHECKER_URL=http://fchecker
      - FORMALZ_FCHECKER_PORT=8080
      # DB config
      - FORMALZ_DB_HOST=db
      - FORMALZ_DB_DATABASE=formalz
      - FORMALZ_DB_USERNAME=admin
      - FORMALZ_DB_PASSWORD=admin
      # Gameserver config
      - FORMALZ_GAMESERVER_PORT=8080
      # Analytics config
      - FORMALZ_ANALYTICS_ENABLED=false
    hostname: formalz-gameserver

  backend:
    image: eucm/formalz-backend:1.0.3
    container_name: formalz-backend
    restart: unless-stopped
    depends_on:
      - gameserver
      - db
      - fchecker
    environment:
      # General params
      - FORMALZ_APP_NAME=Formalz-Analytics
      - "FORMALZ_APP_KEY=base64:guiDZq4HpnsMfvypfUGx6cLDHZ/9HfL1e1sa5ZRIj1E="
      - FORMALZ_APP_ENV=development
      - FORMALZ_APP_DEBUG=false
      - FORMALZ_APP_LOG_LEVEL=info
      - FORMALZ_APP_URL=http://localhost:8080/
      # DB
      - FORMALZ_DB_HOST=db
      - FORMALZ_DB_PORT=3306
      - FORMALZ_DB_DATABASE=formalz
      - FORMALZ_DB_USERNAME=admin
      - FORMALZ_DB_PASSWORD=admin
      # Mail config
      - FORMALZ_MAIL_DRIVER=smtp
      - FORMALZ_MAIL_HOST=mail
      - FORMALZ_MAIL_PORT=25
      - FORMALZ_MAIL_ENCRYPTION=
      # Game websocket config
      - FORMALZ_GAMESERVER_PROTOCOL=ws
      - FORMALZ_GAMESERVER_HOST=formalz.external.test
      - FORMALZ_GAMESERVER_PORT=8080
      - FORMALZ_GAMESERVER_PATH=/gameserver
      # Trusted proxy config
      - INTERNAL_PROXY_HOSTNAME=nginx
      # Admin user config
      - FORMALZ_ADMIN_USERNAME=admin
      - FORMALZ_ADMIN_PASSWORD=secret
      - FORMALZ_ADMIN_EMAIL=admin@example.com
      - FORMALZ_ADMIN_JOB_TITLE=Administrator
      # Analytics config
      - FORMALZ_ANALYTICS_ENABLED=false
    volumes:
      - files:/app/storage
    hostname: formalz-backend


  db:
    image: webhippie/mariadb:latest
    container_name: formalz-db
    restart: always
    hostname: formalz-db
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_USERNAME=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=formalz
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  nginx:
    image: nginx:1.17-alpine
    restart: always
    depends_on:
      - fchecker
      - gameserver
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf-extra.d:/etc/nginx/conf-extra.d