version: '3.7'

services:
  mail:
    image: maildev/maildev:1.1.0
    container_name: "mail"
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    hostname: mail
    ports:
      - 8025:80